del *.log /q/s
del *.sql /q/s
del *.obj /q/s
del *.ilk /q/s
del *.tlb /q/s
del *.tli /q/s
del *.tlh /q/s
del *.tmp /q/s
del *.rsp /q/s
del *.pgc /q/s
del *.pgd /q/s
del *.pdb /q/s
del *.ncb /q/s
del *.idb /q/s
del *.pch /q/s
del *.res /q/s
del BuildLog*.* /q/s